Added store selector to menu footer(#2e5w2hb)
hotwax/threshold-management pull request #103
Opened 2022-05-30 09:58 UTC by azkyakhan

### Related Issues
 

 Closes #

 ### Short Description and Why It's Useful
 

 ### Screenshots of Visual Changes before/after (If There Are Any)
 

 **IMPORTANT NOTICE** - Remember to add changelog entry

 ### Contribution and Currently Important Rules Acceptance
 

 - [ ] I read and followed [contribution rules](https://github.com/hotwax/threshold-management#contribution-guideline)

2022-05-30 10:13 UTC, azkyakhan commented
https://user-images.githubusercontent.com/82817616/170970998-07c72339-3a08-4db3-8815-379687547910.mp4

2022-05-30 10:30 UTC, azkyakhan commented
https://user-images.githubusercontent.com/82817616/170973901-6a9fabaa-24fb-47a5-babe-e6a842d32fd0.mp4

2022-05-30 10:40 UTC, ymaheshwari1 requested changes

2022-05-30 10:40 UTC, ymaheshwari1 commented on src/views/SelectProduct.vue
> +    emitter.on("productStoreChanged", this.getProducts);
```suggestion
    emitter.off("productStoreChanged", this.getProducts);
```

2022-05-30 10:40 UTC, ymaheshwari1 commented on src/views/ThresholdUpdates.vue
> +    emitter.on("productStoreChanged", this.refreshJobs);
```suggestion
    emitter.off("productStoreChanged", this.refreshJobs);
```

2022-05-30 10:50 UTC, azkyakhan commented on src/views/SelectProduct.vue
> +    emitter.on("productStoreChanged", this.getProducts);
I have updated it sir.

2022-05-30 10:50 UTC, azkyakhan commented on src/views/ThresholdUpdates.vue
> +    emitter.on("productStoreChanged", this.refreshJobs);
I have updated it sir.

2023-02-16 09:31 UTC, ymaheshwari1 commented
Closing as handled in #171

2023-02-16 09:31 UTC, closed without merging