Improved: code to create a user search preference entry after creating search preference (#2e5ww56).
hotwax/threshold-management pull request #104
Opened 2022-05-30 11:22 UTC by meet-aniket

### Related Issues
 

 Closes #

 ### Short Description and Why It's Useful
 
:- Worked on improving the code to create a user search preference entry after creating search preference (#2e5ww56).

 ### Screenshots of Visual Changes before/after (If There Are Any)
 

 **IMPORTANT NOTICE** - Remember to add changelog entry

 ### Contribution and Currently Important Rules Acceptance
 

 - [ ] I read and followed [contribution rules](https://github.com/hotwax/threshold-management#contribution-guideline)

2022-06-07 05:25 UTC, adityasharma7 requested changes

2022-06-07 05:25 UTC, adityasharma7 commented on src/components/SaveThresholdModal.vue
> +            "userSearchPrefTypeId": ""
```suggestion
            "userSearchPrefTypeId": "THRESHOLD_INV_QUERY"
```

2022-06-07 05:25 UTC, adityasharma7 commented on src/components/SaveThresholdModal.vue
> +            // TODO: Need to add userSearchPrefTypeId here to associate search preference with the user.
```suggestion
```

2022-06-07 05:25 UTC, adityasharma7 commented on src/components/SaveThresholdModal.vue
> +            // TODO: Need to add userSearchPrefTypeId here to associate search preference with the user.
```suggestion
```

2022-07-18 06:53 UTC, adityasharma7 requested changes

2022-07-18 06:59 UTC, ymaheshwari1 approved these changes

2022-08-09 09:54 UTC, adityasharma7 requested changes

2022-08-09 09:54 UTC, adityasharma7 commented on src/components/SaveThresholdModal.vue
> +          await ProductService.associateSearchPrefToUser(params);
I think we should handle error

2022-08-17 05:56 UTC, shashwatbangar commented on src/components/SaveThresholdModal.vue
> +          await ProductService.associateSearchPrefToUser(params);
Done sir.

2022-08-19 06:13 UTC, merged