Implemented: Toast to display server errors(#2gg32yc)
hotwax/threshold-management pull request #130
Opened 2022-08-17 13:40 UTC by shashwatbangar

### Related Issues
 

 Closes #

 ### Short Description and Why It's Useful
 

 ### Screenshots of Visual Changes before/after (If There Are Any)
 
[Screencast from Wednesday 17 August 2022 05:20:35  IST.webm](https://user-images.githubusercontent.com/62360781/185148856-43994403-84e2-456e-a9b3-cccd57365d9d.webm)

 **IMPORTANT NOTICE** - Remember to add changelog entry

 ### Contribution and Currently Important Rules Acceptance
 

 - [ ] I read and followed [contribution rules](https://github.com/hotwax/threshold-management#contribution-guideline)

2022-09-02 07:21 UTC, adityasharma7 requested changes

2022-09-02 07:21 UTC, adityasharma7 commented on src/utils/index.ts
> +  if(message === "Something went wrong" && err) {
`message === "Something went wrong"`  
I think this check is not needed

2022-09-02 07:21 UTC, adityasharma7 commented on src/utils/index.ts
> +      message,
I thin we could create a initialisation object 
```
{
      message,
      duration: 3000,
      position: 'bottom'
}
```

Add buttons to it if the err is passed

2022-09-02 12:01 UTC, adityasharma7 requested changes

2022-09-02 12:01 UTC, adityasharma7 commented on src/utils/index.ts
> +const checkServerError = (resp: any) => {
Improve method name

2022-09-02 12:16 UTC, adityasharma7 requested changes

2022-09-02 12:16 UTC, adityasharma7 commented on src/store/modules/user/actions.ts
> +        showToast(translate('Something went wrong'), getResponseError(resp));
I think this is not needed

2022-09-02 12:16 UTC, adityasharma7 commented on src/store/modules/user/actions.ts
> -      showToast(translate('Something went wrong'));
I think this is not needed. We should not share any server errors to unauthenticated user

2022-09-02 12:20 UTC, ymaheshwari1 requested changes

2022-09-02 12:20 UTC, ymaheshwari1 commented on src/components/SaveThresholdModal.vue
> +          showToast(translate('Something went wrong'), getResponseError(ifScheduleJobSuccess))
`ifScheduleJobSuccess` contains a boolean value and hence will not contain the server error.

2022-09-02 12:20 UTC, ymaheshwari1 commented on src/utils/index.ts
> +  const error = resp.error || resp.data._ERROR_MESSAGE_ || resp.data._ERROR_MESSAGE_LIST_;
```suggestion
  return resp.data.error || resp.data._ERROR_MESSAGE_ || resp.data._ERROR_MESSAGE_LIST_ || resp.data.errorMessage || resp.data.errorMessageList;
```

2022-09-06 06:31 UTC, adityasharma7 requested changes

2022-09-06 06:31 UTC, adityasharma7 commented on src/store/modules/user/actions.ts
> +import { getResponseError, hasError, showToast } from '@/utils'
I think `getResponseError` is not used anywhere, we could remove the import

2022-09-06 06:31 UTC, adityasharma7 commented on src/utils/index.ts
> +  if(Array.isArray(resp)) {
I think we should handle it from where we are calling it

2022-09-08 14:34 UTC, adityasharma7 approved these changes

2022-09-08 14:34 UTC, merged