Jobs are not refreshed when changing a job from the pipeline page(#2a7yg9j)
hotwax/threshold-management pull request #133
Opened 2022-09-01 14:02 UTC by disha1202

### Related Issues
 

 Closes #

 ### Short Description and Why It's Useful
 

 ### Screenshots of Visual Changes before/after (If There Are Any)
 

 **IMPORTANT NOTICE** - Remember to add changelog entry

 ### Contribution and Currently Important Rules Acceptance
 

 - [ ] I read and followed [contribution rules](https://github.com/hotwax/threshold-management#contribution-guideline)

2022-09-06 13:33 UTC, ymaheshwari1 requested changes

2022-09-06 13:33 UTC, ymaheshwari1 commented on src/store/modules/job/actions.ts
> +        const jobEnums = process.env?.VUE_APP_JOB_ENUMS ? JSON.parse(process.env?.VUE_APP_JOB_ENUMS) : [];
```suggestion
        const jobEnums = process.env?.VUE_APP_JOB_ENUMS ? JSON.parse(process.env.VUE_APP_JOB_ENUMS) : [];
```

2022-09-12 07:05 UTC, adityasharma7 requested changes

2022-09-12 07:05 UTC, adityasharma7 commented on src/components/JobConfiguration.vue
> +import { handleDateTimeInput, hasError } from "@/utils";
I think there are unwanted changes in this file. Please revert

2022-09-12 07:05 UTC, adityasharma7 commented on src/views/ThresholdUpdates.vue
> +          <JobConfiguration :title="title" :job="currentJob" :productCount="productCount" :status="currentJobStatus" :type="freqType" :key="currentJob" :jobEnums="jobEnums" />
I think this may not be needed as we are not using jobEnums in JobConfiguration component

2022-11-01 05:14 UTC, ymaheshwari1 commented
closes #137

2023-02-06 13:32 UTC, adityasharma7 requested changes

2023-02-06 13:32 UTC, adityasharma7 commented on src/components/JobConfiguration.vue
> +              let skipTime = {};
I think this logic should belong to action only
Also, we followed same in Job Manager so would be good for consistency
https://github.com/hotwax/job-manager/blob/main/src/store/modules/job/actions.ts#L562

2023-02-15 09:19 UTC, ymaheshwari1 commented
Fixed in #167
Closing

2023-02-15 09:19 UTC, closed without merging