Fixed: Menu item is displaying as selected(#227)
hotwax/threshold-management pull request #231
Opened 2024-01-09 05:53 UTC by shanmukhdutt

### Related Issues
 

 Closes #277

 ### Short Description and Why It's Useful
 

 ### Screenshots of Visual Changes before/after (If There Are Any)
 Before 
 
![Screenshot from 2024-01-09 11-22-05](https://github.com/hotwax/threshold-management/assets/137382333/da547cc5-7ee2-40fb-9ca3-3370582a53c0)

After

![Screenshot from 2024-01-09 11-18-11](https://github.com/hotwax/threshold-management/assets/137382333/08fa3e91-2387-42e7-8cc9-5c02d77d5159)

 **IMPORTANT NOTICE** - Remember to add changelog entry

 ### Contribution and Currently Important Rules Acceptance
 

 - [ ] I read and followed [contribution rules](https://github.com/hotwax/threshold-management#contribution-guideline)

2024-01-09 11:16 UTC, ymaheshwari1 requested changes

2024-01-09 11:16 UTC, ymaheshwari1 commented on src/components/Menu.vue
> +          mdIcon: settingsOutline
Add support for permission check, as we have support to check for permission for the pages

2024-01-09 11:16 UTC, ymaheshwari1 commented on src/components/Menu.vue
> +      const path = router.currentRoute.value.path
Improve indentation

2024-01-09 11:16 UTC, ymaheshwari1 commented on src/components/Menu.vue
> +          button
Improve indentation

2024-01-15 13:03 UTC, amansinghbais commented on src/components/Menu.vue
> +        selectedIndex
arrange following in alphabetical order.

2024-01-15 13:04 UTC, amansinghbais commented on src/components/Menu.vue
> +        <ion-menu-toggle auto-hide="false" v-for="(p,i) in getValidMenuItems(appPages)" :key="i">
The variables in v-for needs to be explanatory. Don't use character such as p and i.

2024-01-29 07:26 UTC, ymaheshwari1 requested changes

2024-01-29 07:26 UTC, ymaheshwari1 commented on src/components/Menu.vue
> +          url: "/Settings",
```suggestion
          url: "/settings",
```

2024-01-31 14:00 UTC, ymaheshwari1 approved these changes

2024-02-01 10:29 UTC, merged