Implemented: functionality to all the rule pages (#255)
hotwax/threshold-management pull request #256
Opened 2024-04-22 05:44 UTC by amansinghbais

### Related Issues
 

 Related Issue #255

 ### Short Description and Why It's Useful
 
Added the functionality to the following pages
- Safety-stock page
- Store pickup page
- Shipping page

 ### Screenshots of Visual Changes before/after (If There Are Any)
 

 **IMPORTANT NOTICE** - Remember to add changelog entry

 ### Contribution and Currently Important Rules Acceptance
 

 - [x] I read and followed [contribution rules](https://github.com/hotwax/threshold-management#contribution-guideline)

2024-04-22 08:48 UTC, ymaheshwari1 requested changes

2024-04-22 09:25 UTC, amansinghbais commented on src/components/UpdateProductFiltersModal.vue
> +
Fixed this.

2024-04-23 05:02 UTC, ymaheshwari1 requested changes

2024-04-25 05:57 UTC, ymaheshwari1 requested changes

2024-04-25 05:57 UTC, ymaheshwari1 commented on src/components/RuleItem.vue
> +            showToast(translate("Safety stock should be greater then 0."));
```suggestion
            showToast(translate("Safety stock should be greater then or equal to 0."));
```

2024-04-25 05:57 UTC, ymaheshwari1 commented on src/components/RuleItem.vue
> +            showToast(translate("Threshold should be greater then 0."));
```suggestion
            showToast(translate("Threshold should be greater then or equal to 0."));
```

2024-04-25 05:57 UTC, ymaheshwari1 commented on src/components/RuleItem.vue
> +          if(data.safetyStock < 0) {
This check for safetyStock value is redundant. We can move this check above the parent `if`.

2024-04-25 09:03 UTC, merged