(WIP) Implemented: code to add timezone support on the settings page (#2a7ymej).
hotwax/threshold-management pull request #68
Opened 2022-05-10 05:41 UTC by meet-aniket

2022-05-10 09:49 UTC, ymaheshwari1 requested changes

2022-05-10 09:49 UTC, ymaheshwari1 commented on src/components/SaveThresholdModal.vue
> +          'recurrenceTimeZone': this.store.state.user.current.userTimeZone
Use getter to fetch the timezone.

2022-05-10 09:50 UTC, ymaheshwari1 requested changes

2022-05-10 09:50 UTC, ymaheshwari1 commented on src/views/TimezoneModal.vue
> +                }
Improve indentation.

2022-05-10 10:06 UTC, meet-aniket commented on src/components/SaveThresholdModal.vue
> +          'recurrenceTimeZone': this.store.state.user.current.userTimeZone
Sir, update code.

2022-05-10 10:06 UTC, meet-aniket commented on src/views/TimezoneModal.vue
> +                }
Sir, improved code.

2022-05-11 07:19 UTC, ymaheshwari1 requested changes

2022-05-11 07:19 UTC, ymaheshwari1 commented on src/components/JobConfiguration.vue
> +      return DateTime.fromMillis(time, { zone: this.getUserProfile.userTimeZone }).toLocaleString(DateTime.TIME_SIMPLE);
```suggestion
      return DateTime.fromMillis(time, { zone: this.getUserProfile.userTimeZone }).toLocaleString(DateTime.DATETIME_MED);
```

2022-05-11 11:55 UTC, meet-aniket commented on src/components/JobConfiguration.vue
> +      return DateTime.fromMillis(time, { zone: this.getUserProfile.userTimeZone }).toLocaleString(DateTime.TIME_SIMPLE);
Improved code Sir.

2022-05-24 12:27 UTC, adityasharma7 requested changes

2022-05-24 12:27 UTC, adityasharma7 commented on src/components/JobConfiguration.vue
> +      getUserProfile: 'user/getUserProfile'
```suggestion
      userProfile: 'user/getUserProfile'
```

2022-05-24 12:27 UTC, adityasharma7 commented on src/components/JobHistoryModal.vue
> +      getUserProfile: 'user/getUserProfile'
```suggestion
      userProfile: 'user/getUserProfile'
```

2022-05-24 12:27 UTC, adityasharma7 commented on src/views/TimezoneModal.vue
> +      <ion-searchbar @ionFocus="selectSearchBarText($event)" :placeholder="$t('Search time zones')"  v-model="queryString" @ionInput="findTimeZone()" />
This should work enter

2022-05-24 12:27 UTC, adityasharma7 commented on src/views/TimezoneModal.vue
> +      <ion-searchbar @ionFocus="selectSearchBarText($event)" :placeholder="$t('Search time zones')"  v-model="queryString" @ionInput="findTimeZone()" />
Also, we should handle text mismatch

2022-05-24 12:27 UTC, adityasharma7 commented on src/views/TimezoneModal.vue
> +            return DateTime.local().setZone(timeZone.id).isValid;
Add comment why we are doing this?

2022-05-24 16:11 UTC, meet-aniket commented on src/components/JobConfiguration.vue
> +      getUserProfile: 'user/getUserProfile'
Sir, updated code.

2022-05-24 16:13 UTC, meet-aniket commented on src/components/JobHistoryModal.vue
> +      getUserProfile: 'user/getUserProfile'
Sir, updated code.

2022-05-24 17:32 UTC, meet-aniket commented on src/views/TimezoneModal.vue
> +      <ion-searchbar @ionFocus="selectSearchBarText($event)" :placeholder="$t('Search time zones')"  v-model="queryString" @ionInput="findTimeZone()" />
Sir, updated code.

2022-05-25 06:01 UTC, merged