Fixed build console warnings (threshold-management/#69)
hotwax/threshold-management pull request #71
Opened 2022-05-10 12:04 UTC by rathoreprashant

#Removed Unwanted Definitions and Assignments
**Definitions**
- `img.onerror = function (**error**)`
- `import { **translate** } from "@/i18n";`
- `setUserInstanceUrl ({ **state**, commit }, payload){`
-  `async getEComStores({ **commit** }, payload) {`
- `async setEComStore({ commit, **dispatch** }, payload) {`
- `import { **IonBackButton**, IonButton, IonContent, IonHeader,IonIcon, IonItem, IonLabel, IonMenuButton, IonPage, IonSelect, IonSelectOption, IonTitle, IonToolbar, **popoverController** } from '@ionic/vue';`
- `import emitter from '@/event-bus';` 

**Assignments**
- `const **cachedEnum** = payload.map((id: any) => state.enumIds[id]);`
-  `const **cachedTempExpr** = tempExprIds.map((id: any) => state.temporalExp[id]);`

2022-05-10 12:25 UTC, ymaheshwari1 requested changes
We will not push the package-lock.json file until we do not make any change in the package.json file.

2022-05-10 12:29 UTC, rathoreprashant commented
> We will not push the package-lock.json file until we do not make any change in the package.json file.

ok sir I'll

> We will not push the package-lock.json file until we do not make any change in the package.json file.

2022-05-10 12:46 UTC, rathoreprashant commented
Reopen,
By mistake, I closed this PR.

2022-05-10 12:47 UTC, rathoreprashant commented
Reopen,
By mistake, I closed this PR.

2022-05-10 12:50 UTC, rathoreprashant commented
Ok, sir I'll not push it from next time

2022-05-11 07:09 UTC, adityasharma7 requested changes

2022-05-11 07:09 UTC, adityasharma7 commented on src/store/modules/user/actions.ts
> +  async getEComStores(payload) {
I think this will cause abrupt behaviour of this action. If we are not doing anything related to state we should rather create service

2022-05-23 06:50 UTC, adityasharma7 requested changes

2022-05-23 06:50 UTC, adityasharma7 commented on src/store/modules/user/actions.ts
> +        const newresp = await UserService.getEComStores(payload);
Improve variable name
https://google.github.io/styleguide/jsguide.html

2022-05-23 07:53 UTC, rathoreprashant commented on src/store/modules/user/actions.ts
> +        const newresp = await UserService.getEComStores(payload);
Improved sir Please have a look

2022-05-24 05:58 UTC, adityasharma7 approved these changes

2022-05-24 05:58 UTC, merged