Improved: code to refresh the jobs when changing a job from the pipeline page (#2a7yg9j).
hotwax/threshold-management pull request #74
Opened 2022-05-11 05:16 UTC by meet-aniket

### Related Issues

Closes #

### Short Description and Why It's Useful

Worked on improving the code and dispatching the `fetchJobs` action after getting a response back `updateJob` to refresh the jobs when changing a job from the pipeline page.

### Screenshots of Visual Changes before/after (If There Are Any)

https://user-images.githubusercontent.com/52008359/167770220-3712c297-c40f-49c9-a4c6-d7274e349f49.mp4

**IMPORTANT NOTICE** - Remember to add a changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

2022-05-19 06:33 UTC, adityasharma7 requested changes

2022-05-19 06:33 UTC, adityasharma7 commented on src/components/JobConfiguration.vue
> +            await this.store.dispatch('job/fetchPendingJobs', { eComStoreId: this.getCurrentEComStore.productStoreId, viewSize: process.env.VUE_APP_VIEW_SIZE, viewIndex: 0, jobEnums: this.jobEnums })
I think this will dispatch even when user is updating job from page other than pipeline page. This should be properly handled.

2022-05-19 06:33 UTC, adityasharma7 commented on src/components/JobConfiguration.vue
> +      getCurrentEComStore:'user/getCurrentEComStore'
We already have it as  `currentEComStore`

2023-02-10 03:55 UTC, ymaheshwari1 commented
Closing as already handled.

2023-02-10 03:55 UTC, closed without merging